### ISSUE TITLE
Revisit parts of the spec to benefit from compatibility

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-specs#185]
## Summary

I think some parts spec still deviate from existing implementations in the Cosmos-SDK. In some cases this might inevitable (e.g. changes to the staking logic to make it efficiently fraud provable) in other cases the changes might be purely cosmetic, small improvements, or, simply do not account for the existing implementation. In some cases these little changes break compatibility to existing Cosmos infrastructure where it is not really required. These should be resisted.

This issue is about revisiting the spec from this perspective, to list all these places and to tack if any changes need to be made.

### Details

This should (eventually) contain an exhaustive list of changes:
- [ ] SDK Txs have two kind of nonces: account number and account sequence (spec only has nonce); which already led to  including yet another Nonce field in implementation following the spec: https://github.com/celestiaorg/lazyledger-app/blob/0e60861ff7f5548d52391f5aa57014e2554bbbff/x/lazyledgerapp/types/tx.pb.go#L36 (cc @evan-forbes)
- [ ] verify compatibility of all Tx types with SDK Txs (so they can be signed by a ledger without substantially modifying the software); same with the encoding
- [ ] ...

### Action Items
- [ ] Complete above list 
- [ ] Change all uncontroversial places in the spec (if necessary at all)
- [ ] discuss the others + their impact

### Refs
https://github.com/celestiaorg/lazyledger-app/issues/33

**Comment by adlerjohn** [comment]
Using app
